# Generated by Django 4.2.1 on 2023-05-29 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutTracker', '0003_workout_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
    ]
