# Generated by Django 4.2.1 on 2023-05-29 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workoutTracker', '0004_remove_workout_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='workouts',
            new_name='workout',
        ),
    ]
