# Generated by Django 4.2.1 on 2023-05-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutTracker', '0005_rename_workouts_exercise_workout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(related_name='workouts', to='workoutTracker.exercise'),
        ),
    ]
