# Generated by Django 4.2.1 on 2023-06-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutTracker', '0007_plannedday_workout_planned_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='planned_days',
        ),
        migrations.AddField(
            model_name='plannedday',
            name='workouts',
            field=models.ManyToManyField(related_name='planned_days', to='workoutTracker.workout'),
        ),
    ]
