# Generated by Django 4.2.1 on 2023-12-13 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutTracker', '0008_remove_workout_planned_days_plannedday_workouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('workouts', models.ManyToManyField(related_name='recorded_days', to='workoutTracker.workout')),
            ],
        ),
    ]
