# Generated by Django 4.2.1 on 2023-12-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutTracker', '0009_recordedday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
